name: Build .NET Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.127'

    - name: Restore dependencies
      run: dotnet restore LearningPlatform/LearningPlatform.sln

    - name: Build
      run: dotnet build LearningPlatform/LearningPlatform.sln --configuration Release --no-restore
